# Generated by Django 4.2.6 on 2023-11-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, help_text="Enter your GitHub URL"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="Enter your LinkedIn URL"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Enter your Facebook URL"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Enter your Instagram URL"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
