# Generated by Django 4.2.6 on 2023-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="email",
            field=models.URLField(
                blank=True, help_text="Enter your Email Address here"
            ),
        ),
    ]
