# Generated by Django 4.2.6 on 2023-11-25 14:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("site_settings", "0002_socialmediasettings_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Enter your Email Address here", max_length=254
            ),
        ),
        migrations.CreateModel(
            name="FooterConent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footer_content", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
