# Generated by Django 4.2.6 on 2023-11-25 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("site_settings", "0003_alter_socialmediasettings_email_footerconent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FooterConent",
            new_name="FooterContent",
        ),
    ]
