# Generated by Django 4.2.6 on 2023-11-25 14:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0005_rename_footer_content_footercontent_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footercontent",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="footer_title_slug", editable=True, populate_from="title"
            ),
        ),
    ]
