# Generated by Django 4.2.6 on 2023-11-25 15:10

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("site_settings", "0006_footercontent_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediasettings",
            name="email",
        ),
        migrations.AlterField(
            model_name="footercontent",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="slug", editable=True, populate_from="title"
            ),
        ),
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter your Email Address here",
                        max_length=254,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
