# Generated by Django 4.2.6 on 2023-11-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0007_remove_socialmediasettings_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsettings",
            name="show_email",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
