# Generated by Django 4.2.6 on 2023-11-19 14:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0003_menuitem_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=True, populate_from="title"),
        ),
    ]
